<div id="rXI---textarea" contenteditable="true"></div>
<div id="rXI---author"></div>

<div id="rXI---slug">{0:SA:%100%_}</div>
<div id="rXI---score">{10:SA:%10%1~%20%2~%30%3~%40%4~%50%5~%60%6~%70%7~%80%8~%90%9~%100%10}</div>

<script type="application/javascript">
    var rXI$h = {
            au:  'К. Г. Паустовский',
            te:  'Вокруг нашего дома стояли задумавшись огромные каштаны.',
            pu: [0,     0,     0,   0,     1,          1,       0,      8],
            ma: [0,     0,     0,   0,     1,          1,       0,      0],
        };
</script>
