
{% set AUTHOR = 'Н. А. Некрасов' %}

{% set TEXT =              'Я ваш покой смутить моим признаньем благоговея никогда не смел.' %}
{% set PUNCTUATION_MAP = '[0,0,  0,    0,      0,   0,         1,         1,      0, 0,   8]' %}
{% set ANSWERS_MASK =    '[0,0,  0,    0,      0,   0,         1,         1,      0, 0,   0]' %}
{% set RIGHT_SLUG =        '| | | | | |, |, | | |.' %}

{% include 'inc/punctuation.inc' %}
