<div class="rXI---sentences">

<div class="rXI---sentence">
    1. Больше
    <span class="nobr">мес<span class="rXI---input" data-placeholder="…">{% if HTML %}<input/>{% else %}{1:SA:%100%я}{% endif %}</span>ца,</span>
    до двадцатого июня, пришлось мне прожить в Центральном лагере,
    <span class="nobr">спрята<span class="rXI---input" data-placeholder="…">{% if HTML %}<input/>{% else %}{1:SA:%100%нн}{% endif %}</span>ом</span>
    глубоко в ущелье красных и
    <span class="nobr">ж<span class="rXI---input" data-placeholder="…">{% if HTML %}<input/>{% else %}{1:SA:%100%ё~%100%е}{% endif %}</span>лтых</span>
    меловых
    <span class="nobr">песча<span class="rXI---input" data-placeholder="…">{% if HTML %}<input/>{% else %}{1:SA:%100%н}{% endif %}</span>иков.</span>
    <span class="rXI---author">(Ефр.)</span>
</div>

</div>
