<div class="rXI---sentences">

<div class="rXI---sentence">
    1. Больше
    <span class="nobr">мес<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%я}{% endif %}</span>ца,</span>
    до двадцатого июня, пришлось мне прожить в Центральном лагере,
    <span class="nobr">спрята<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ом</span>
    глубоко в ущелье красных и
    <span class="nobr">ж<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%ё~%100%е}{% endif %}</span>лтых</span>
    меловых
    <span class="nobr">песча<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%н}{% endif %}</span>иков.</span>
    <span class="rXI---author">(И. Ефремов)</span>
</div>

<div class="rXI---sentence">
    2.
    <span class="nobr">Остриже<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ый</span>
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(под)машинку">{% if HTML %}<input/>{% else
    %}{1:SA:%100%под машинку~%100%под  машинку}{% endif %}</span>,</span>
    худой,
    <span class="nobr">заг<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%о~%100%o}{% endif %}</span>ревший</span>
    до фиолетовой черноты Пресняков
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(не)устрашимо">{% if HTML %}<input/>{% else
    %}{1:SA:%100%неустрашимо}{% endif %}</span></span>
    сидел
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(на)корточках">{% if HTML %}<input/>{% else
    %}{1:SA:%100%на корточках~%100%на  корточках}{% endif %}</span></span>
    на узкой ступеньке в отвесном обрыве.
    <span class="rXI---author">(И. Ефремов)</span>
</div>

<div class="rXI---sentence">
    3. Слушая генерал смотрел
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(в)низ">{% if HTML %}<input/>{% else
    %}{1:SA:%100%вниз}{% endif %}</span>,</span>
    склонив морщинистую шею.
    <span class="rXI---author">(А. Бек)</span>
</div>

<div class="rXI---sentence">
    4. Дед
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(не)ожиданно">{% if HTML %}<input/>{% else
    %}{1:SA:%100%неожиданно}{% endif %}</span></span>
    продал дом кабатчику, купив другой, по
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(К, к)анатной">{% if HTML %}<input/>{% else
    %}{1:SA:%100%Канатной}{% endif %}</span></span>
    улице; <span class="nobr">немоще<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%н}{% endif %}</span>ая,</span>
    заросшая травою, чистая и тихая, она выходила прямо в поле и была
    снизана из маленьких, пестро
    <span class="nobr">окраше<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ых</span>
    домиков. <span class="rXI---author">(М. Горький)</span>
</div>

<div class="rXI---sentence">
    5. Он
    <span class="nobr">прош<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%ё~%100%е}{% endif %}</span>л</span>
    в высокое помещение и, тихо прикрыв дверь,
    <span class="rXI---input"
    data-placeholder="(не)слышно">{% if HTML %}<input/>{% else
    %}{1:SA:%100%неслышно}{% endif %}</span>
    остановился, смотря на <span class="nobr">пос<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%е}{% endif %}</span>девшую</span>
    женщину в <span class="nobr">ч<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%ё~%100%е}{% endif %}</span>рном</span> платье. <span
    class="rXI---author">(А. Грин)</span>
</div>

<div class="rXI---sentence">
    6. Весь день Анна провела дома,
    <span class="rXI---input"
    data-placeholder="(то)есть">{% if HTML %}<input/>{% else
    %}{1:SA:%100%то есть}{% endif %}</span>
    у Облонских, и не принимала
    <span class="rXI---input"
    data-placeholder="(н…)кого">{% if HTML %}<input/>{% else
    %}{1:SA:%100%никого}{% endif %}</span>.
    <span class="rXI---author">(Л. Н. Толстой)</span>
</div>

<div class="rXI---sentence">
    7. В двадцати шагах от палаток, на поляне,
    <span class="nobr">ограниче<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ой</span>
    с трех сторон кустарником, а с одной стороны горной рекой, начинающие
    альпинисты занимались зарядкой.
    <span class="rXI---author">(В. Солоухин)</span>
</div>

<div class="rXI---sentence">
    8.
    <span class="rXI---input"
    data-placeholder="(Н…)кого">{% if HTML %}<input/>{% else
    %}{1:SA:%100%Никого}{% endif %}</span> не будет в доме кроме
    <span class="nobr">сумер<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%е}{% endif %}</span>к.</span> <span
    class="rXI---author">(Б. Пастернак)</span>
</div>

<div class="rXI---sentence">
    9. Чуть сутулясь, вобрав голову в плечи, он [Панфилов] сидел за большим
    <span class="nobr">письме<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ым</span>
    столом, просматривая
    <span class="rXI---input"
    data-placeholder="какие(то)">{% if HTML %}<input/>{% else
    %}{1:SA:%100%какие-то}{% endif %}</span>
    бумаги. <span class="rXI---author">(А. Бек)</span>
</div>

<div class="rXI---sentence">
    10. На сцене, сияя умиленной актерской улыбкой, стояла, вся
    <span class="nobr">в <span class="rXI---input"
    data-placeholder="брил…иантах">{% if HTML %}<input/>{% else
    %}{1:SA:%100%бриллиантах}{% endif %}</span>,</span>
    госпожа Шевалье. <span class="nobr">У <span class="rXI---input"
    data-placeholder="бар…ера">{% if HTML %}<input/>{% else
    %}{1:SA:%100%барьера}{% endif %}</span>,</span>
    отделявшего залу от сцены, толпилась
    <span class="nobr"><span class="rXI---input"
    data-placeholder="молодеж…">{% if HTML %}<input/>{% else
    %}{1:SA:%100%молодежь}{% endif %}</span>,</span>
    восторгу которой кисло снисходительно улыбались, подбирая под себя ноги,
    важные люди, сидевшие в первом ряду партера.
    <span class="rXI---author">(М. Алданов)</span>
</div>

<div class="rXI---sentence">
    11.
    <span class="rXI---input"
    data-placeholder="Цыганка(гадалка)">{% if HTML %}<input/>{% else
    %}{1:SA:%100%Цыганка-гадалка}{% endif %}</span>
    стоит у дороги и ярко смеется, сверкая белыми зубами, сама
    темная, вся <span class="nobr">заг<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%о}{% endif %}</span>релая,</span>
    в лохмотьях красной юбки, босая, с растрепавшейся по ветру
    косой. <span class="rXI---author">(Ф. Сологуб)</span>
</div>

</div>
