<div class="rXI---sentences">

<div class="rXI---sentence">
    1. Больше
    <span class="nobr">мес<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%я}{% endif %}</span>ца,</span>
    до двадцатого июня, пришлось мне прожить в Центральном лагере,
    <span class="nobr">спрята<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ом</span>
    глубоко в ущелье красных и
    <span class="nobr">ж<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%ё~%100%е}{% endif %}</span>лтых</span>
    меловых
    <span class="nobr">песча<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%н}{% endif %}</span>иков.</span>
    <span class="rXI---author">(И. Ефремов)</span>
</div>

<div class="rXI---sentence">
    2.
    <span class="nobr">Остриже<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%нн}{% endif %}</span>ый</span>
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(под)машинку">{% if HTML %}<input/>{% else
    %}{1:SA:%100%под машинку~%100%под  машинку}{% endif %}</span>,</span>
    худой,
    <span class="nobr">заг<span class="rXI---input"
    data-placeholder="...">{% if HTML %}<input/>{% else
    %}{1:SA:%100%о~%100%o}{% endif %}</span>ревший</span>
    до фиолетовой черноты Пресняков
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(не)устрашимо">{% if HTML %}<input/>{% else
    %}{1:SA:%100%неустрашимо}{% endif %}</span></span>
    сидел
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(на)корточках">{% if HTML %}<input/>{% else
    %}{1:SA:%100%на корточках~%100%на  корточках}{% endif %}</span></span>
    на узкой ступеньке в отвесном обрыве.
    <span class="rXI---author">(И. Ефремов)</span>
</div>

<div class="rXI---sentence">
    3. Слушая генерал смотрел
    <span class="nobr"><span class="rXI---input"
    data-placeholder="(в)низ">{% if HTML %}<input/>{% else
    %}{1:SA:%100%вниз}{% endif %}</span>,</span>
    склонив морщинистую шею.
    <span class="rXI---author">(А. Бек)</span>
</div>

</div>
